### PR TITLE
Check if separate shipping address is enabled

### PR DESCRIPTION
**Pull request by mntzrr**
Fixes an issue with the hidden WC form not being updated accordingly when the shipping address is changed. Usually, this is noticed when switching between countries with different VAT, but the tax amount stays the same.

### CODE REVIEW

**Comment by NiklasHogefjord** [comment]
Remember to minify the js file @montazarr  :)

**Comment by pkvillanueva** [comment]
@NiklasHogefjord @montazarr When can this be merged?

**Comment by NiklasHogefjord** [comment]
@mntzrr @pkvillanueva, We will not include this change in the new version. We will start with a smaller bug fix and see if that solves the current issue.

Current live version includes [this check](https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/2.8.5/assets/js/klarna-checkout-for-woocommerce.js#L495). 

That if statement will always be true ( `if( $( '#shipping_first_name' ).length >= 0 ) {}` ). Instead we changed this to `if( $( '#shipping_first_name' ).length > 0 ) {}`. See the commit here: https://github.com/krokedil/klarna-checkout-for-woocommerce/commit/ba96845cc2061432eba19246c898828fae4632fb

**Comment by MichaelBengtsson** [comment]
Closed since this was fixed in a different commit

**Pull request closed without merging**
