### PR TITLE
Change order review table selector to support themes without <table>tag

### PR DESCRIPTION
**Pull request by marcusforsberg**
I'm using a custom theme where the order review table has been replaced and is no longer a `table` but a `div`. It still has the same class as usual, `woocommerce-checkout-review-order-table`.

This breaks the `shipping_address_change` JS callback (in klarna-checkout-for-woocommerce.js) since the selector expects the order review table to specifically be a table: `$('table.woocommerce-checkout-review-order-table')`.

This commit changes the selector to omit the `table` part so it works for themes that don't have a <table> tag.

### CODE REVIEW

**Comment by slobodan** [comment]
@marcusforsberg makes perfect sense to do this, but can you change the PR so it goes to our `develop` branch?

If that's too much hassle, just let me know and I'll make the changes in `develop` directly.

Either way, thank you for the PR!

**Comment by marcusforsberg** [comment]
@slobodan No worries, I've changed it now. 😄

**Comment by slobodan** [comment]
@marcusforsberg I appreciate it! Didn't know you could just change the branch in PR, so thanks for teaching me that :)

**Comment by marcusforsberg** [comment]
@slobodan neither did I to be honest... 😅 Thanks for the merge!

**Pull request merged**
